module.exports = {
    circleOfFifth: [
        ['c', 'a'],
        ['g', 'e'],
        ['d', 'b'],
        ['a', 'f#'],
        ['e', 'c#'],
        ['b', 'g#'],
        ['gb', 'eb'],
        ['db', 'bb'],
        ['ab', 'f'],
        ['eb', 'c'],
        ['bb', 'g'],
        ['f', 'd'],
    ],
    allNotes : [
        ['a'],
        ['a#', 'bb'],
        ['b'],
        ['c'],
        ['c#', 'db'],
        ['d'],
        ['d#', 'eb'],
        ['e'],
        ['f'],
        ['f#', 'gb'],
        ['g'],
        ['g#', 'ab'],
    ]
}
